language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: x9HjXa6zlnsnWw1J5dAcHi85r5r8FV1vz0stUkHTwhpBQfO3ktvBrvai3sMt9GjOCm+3g16craoCLX23x/eJbNObVl8eGHcEKJmQbjerjdbMpFwqzjWXKGT79Th/yIt3dNwTg3xGSIfClOmUEZ0ei2gZmk8w/+EGRklnlBdKUavh3pGGHN/5l/5/UP9AppQnBRNiJGMtJY3IUcGGOZQyRi2rl1e1pHEL27j6IOkAV+EXA4V6d63jAjvadnk+8HtRnIIe+mP3QIXtK9fYcyIxeJclHD9D7GMSi/VAGHrMUHQg+pjGSKUBgNOUwdiJ37g+necMcInlkOrNT4w9VJ3VxGX8Bk3ZjIg4rawUn1haf4JJjh/pZsKPb9tQA3Ig7kNWkJJfhazMiQqi3NwvMoWlxFfukSU4B8PWBRR/1SDKCqq1v8qigRSilCddG9A1pgJZLEm/Mf7epJ4s+j99Vwtff2l2GHV5qcNKeNEXKsApJ4NSd7Lc8drFqTE4lAf4TFOlG1dqN4I+/RFtGxIo8seKeseXNt2Z6vfr9iO3qsvqReiukfldB8HKlGfifjq20HjPqwLzoh/GOGr+ZnYe27SYul4XfIX/VvouiWUKlowGzZ/CRr8BWpbBgPUH7POP2Kj65IT/KRP3Log07fmBNAkikkJ7jaZm7Q+8iwz9DRCgYMk=
  app: developeer
  on:
    repo: fastlain/developeer-client
